version: '3.8'
sevices:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 3005:3005
    networks:
      - common-network

  mysql-container:
    image: mysql
    volumes:
      - /data/apps/docker-data/mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - common-network

networks:
  common-network:
    driver: bridge